spring.application.name=servigestor360

# ============================================
# CONFIGURACIÓN DEL SERVIDOR SPRING BOOT
# ============================================

# Puerto donde se ejecutará la aplicación
server.port=${PORT:8080}


# ============================================
# CONFIGURACIÓN DE LA BASE DE DATOS MYSQL
# ============================================

# URL de conexión a la base de datos
# localhost = servidor local
# 3306 = puerto por defecto de MySQL
# servigestor360db = nombre de la base de datos
spring.datasource.url=${DB_URL}

# Usuario de MySQL
spring.datasource.username=${DB_USERNAME}


# Contraseña de MySQL
spring.datasource.password=${DB_PASSWORD}

# Driver JDBC de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ============================================
# CONFIGURACIÓN JPA / HIBERNATE
# ============================================

# update:
# crea tablas si no existen
# actualiza columnas sin borrar información
spring.jpa.hibernate.ddl-auto=update


# Muestra las consultas SQL en consola
spring.jpa.show-sql=false


# Formatea las consultas SQL para que se vean organizadas
spring.jpa.properties.hibernate.format_sql=false


# ============================================
# CONFIGURACIÓN DE CODIFICACIÓN
# ============================================

# Permite manejar caracteres especiales correctamente
spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4


# ============================================
# MENSAJES DE CONSOLA
# ============================================

# Muestra información detallada de Hibernate
logging.level.org.hibernate.SQL=INFO

# ============================================
# CONFIGURACIÓN OPEN-IN-VIEW
# ============================================

# Evita que Hibernate mantenga abierta
# la conexión a la base de datos durante
# el proceso de renderizado de vistas.
#
# Mejora buenas prácticas de arquitectura
# y evita consultas inesperadas fuera
# de la capa de servicio.
#
# Se recomienda usar false en aplicaciones
# modernas Spring Boot.
spring.jpa.open-in-view=false


# ============================================
# CONFIGURACIÓN JWT
# ============================================

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
